export const dummySkills: SkillRecord[] = [
  {
    id: "1",
    title: "Web Search",
    slug: "web-search",
    description: "Performs real-time web searches and returns summarized results from top sources.",
    category: "Research",
    tags: ["search", "web", "retrieval"],
    installCommand: "npx skild add web-search",
    createdAt: "2026-04-01T10:00:00Z",
    authorClerkId: "user_abc123",
    authorEmail: "alice@example.com",
  },
  {
    id: "2",
    title: "Code Executor",
    slug: "code-executor",
    description: "Executes sandboxed code snippets in Python, JavaScript, or TypeScript and returns output.",
    category: "Development",
    tags: ["code", "execution", "sandbox"],
    installCommand: "npx skild add code-executor",
    createdAt: "2026-04-05T14:30:00Z",
    authorClerkId: "user_def456",
    authorEmail: "bob@example.com",
  },
  {
    id: "3",
    title: "PDF Reader",
    slug: "pdf-reader",
    description: "Extracts and parses text content from PDF documents for downstream processing.",
    category: "Data",
    tags: ["pdf", "parsing", "extraction"],
    installCommand: "npx skild add pdf-reader",
    createdAt: "2026-04-08T09:15:00Z",
    authorClerkId: "user_ghi789",
    authorEmail: "carol@example.com",
  },
  {
    id: "4",
    title: "Image Captioner",
    slug: "image-captioner",
    description: "Generates descriptive captions for images using a vision-language model.",
    category: "Vision",
    tags: ["image", "caption", "multimodal"],
    installCommand: "npx skild add image-captioner",
    createdAt: "2026-04-12T11:45:00Z",
    authorClerkId: "user_jkl012",
    authorEmail: "dave@example.com",
  },
  {
    id: "5",
    title: "Memory Store",
    slug: "memory-store",
    description: "Provides persistent key-value memory for agents to store and retrieve context across sessions.",
    category: "Memory",
    tags: ["memory", "storage", "context"],
    installCommand: "npx skild add memory-store",
    createdAt: "2026-04-18T16:00:00Z",
    authorClerkId: "user_mno345",
    authorEmail: "eve@example.com",
  },
];
