# This is a file for you to write an un-named mutation. 
# Only one un-named mutation is allowed per file.
mutation {
  user_insert(data: {clerkId: "user_3CjnnC5zVgZqXzWCCkw1IShKQkA", email: "brandon@brandonperfetti.com", imageUrl: "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2ltYWdlcy5jbGVyay5kZXYvb2F1dGhfZ2l0aHViL2ltZ18zQ2pubkE4ZTFuOUxIcU91QjV4Mld4OUZ1UmMifQ", username: "brandonperfetti"})
}